language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

cache: npm

jobs:
  include:
    - script: npm test
    - if: env(TRAVIS_NODE_VERSION) NOT IN (4, 5)
      script: npm run dtslint



