language: node_js

node_js:
  - "6"
  - "7"
  - "8"

cache: npm

matrix:
  include:
    - node_js: "4"
      env: RUN_DTS_LINT=false
    - node_js: "5"
      env: RUN_DTS_LINT=false

script:
  - npm test
  - if [[ "$RUN_DTS_LINT" = true ]]; then npm run dtslint; fi
