language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

cache: npm

stages:
  - test
  - name: dtslint
    if: env(TRAVIS_NODE_VERSION) NOT IN(4, 5)

jobs:
  include:
    - stage: test
      script: npm test
    - stage: dtslint
      script: npm run dtslint

